In [7]:
import pandas as pd 



df = pd.read_csv('chesterfield_25-08-2021_09-00-00.csv')

,25/08/2021 09:00,Chesterfield,Richard Copeland,"Regular Flavoured iced latte - Hazelnut - 2.75, Large Latte - 2.45",5.2,CARD,5494173772652516
0,25/08/2021 09:02,Chesterfield,Scott Owens,"Large Flavoured iced latte - Caramel - 3.25, R...",17.30,CARD,6.844802e+15
1,25/08/2021 09:04,Chesterfield,Francis Strayhorn,"Large Flat white - 2.45, Regular Latte - 2.15",4.60,CARD,9.557104e+15
2,25/08/2021 09:06,Chesterfield,Rodney Drake,"Regular Flavoured latte - Hazelnut - 2.55, Lar...",5.00,CARD,2.978328e+15
3,25/08/2021 09:08,Chesterfield,Michael Sparrow,"Regular Latte - 2.15, Large Latte - 2.45",4.60,CASH,NaN
4,25/08/2021 09:10,Chesterfield,Thomas Register,"Large Flavoured iced latte - Caramel - 3.25, R...",12.95,CASH,NaN